import Image from "next/image";
import { ContactList } from "./contact-list";
import "./globals.css";
import { NewContactForm } from "./new-contact-form";
import { SearchForm } from "./search-form";

export type Contact = {
  id: number;
  createdAt: number; // timestamp
  first?: string;
  last?: string;
  favorite?: boolean;
  avatar?: string;
  twitter?: string;
  notes?: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const contacts = await fetch(`http://localhost:8098/contacts`).then(
    (r) => r.json() as Promise<Contact[]>
  );

  return (
    <html lang="en">
      <head>
        <title>TODO React-Router 6 With Next 13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        style={{
          height: `100vh`,
          display: `flex`,
        }}
      >
        <div id="sidebar">
          <h1 style={{ display: "flex", gap: "1rem" }}>
            <Image src="/nextjs.svg" alt="NextJS Logo" width={72} height={16} />{" "}
            13 Contacts
          </h1>
          <div>
            <SearchForm />
            <NewContactForm />
          </div>

          <nav>
            <ContactList contacts={contacts} />
          </nav>
        </div>

        <div id="detail">{children}</div>
      </body>
    </html>
  );
}
